### PR TITLE
update language code format

### PR DESCRIPTION
**Pull request by tomaskikutis**
SDCP-311

### CODE REVIEW

**Review by ride90 — COMMENTED** [review]
I wonder if these 2 broken unit tests are connected to these changes?

**Comment by tomaskikutis** [comment]
Looks like they could be. Could you check it out? I'm not that good at navigating server code apart from searching and replacing :D

**Comment by ride90** [comment]
Will do it.

**Comment by ride90** [comment]
@tomaskikutis btw, ensure that this changes will be reflected after `python manage.py app:initialize_data`. I think you should increment `init_version` in the CV

**Comment by MarkLark86** [comment]
What ticket is this PR for?

**Comment by tomaskikutis** [comment]
Initially, I needed it for SDCP-293. Oleg told this wasn't straight-forward to change so I implemented a workaround and we are leaving this for another release. I've created `SDCP-311` for this.

**Pull request closed without merging**
