### PR TITLE
Use preview for all renditions mapping. [SDCP-256]

### PR DESCRIPTION
**Pull request by GyanP**
main always needs the API key to append in it href whereas preview and thumbnail don't need the API key to append in its href so that we can format the main by appending the API key in it. But then it will give us the original resolutions which we don't want for cp images because cp images resolutions should be around 500*400. Therefore we need a preview for original as well.

### CODE REVIEW

**Comment by petrjasek** [comment]
are you sure we shouldn't fetch original?

**Comment by GyanP** [comment]
> are you sure we shouldn't fetch original?

Since it is not required yet, there is no need to fetch original. If required we can do it in the future.

**Comment by petrjasek** [comment]
I think it is required now, right @karelpetrak ?

**Comment by GyanP** [comment]
This is what Gideon told me:

Slack_Gideon_Lehmann_Sourcefabric (2)

**Comment by petrjasek** [comment]
yep but not sure we can pull another size when distributing, we have that api key around when ingesting

**Comment by karelpetrak** [comment]
Hi guys, @GyanP I am afraid we need the original image due to the distribution logic. So pls adjust the code.

**Pull request merged**
