### PR TITLE
auto tagger

### PR DESCRIPTION
**Pull request by tomaskikutis**
copied from https://github.com/superdesk/superdesk-client-core/pull/4409

### CODE REVIEW

**Comment by cpefatimaabdillahi** [comment]
Hi Tomas, 

Thanks for creating the branch. 

We will restore superdesk-client-core/scripts/extensions/auto-tagging-widget directory and remove the extension from superdesk-cp/client/index.js. 

Thanks

**Comment by tomaskikutis** [comment]
No need to restore anything in superdesk-client-core. I've closed the pull request in `superdesk-client-core` so no changes will be done by it. Do continue your work in `auto-tagger` branch of `superdesk-cp` repository (this one that is used by this pull request).

**Comment by tcp-bhargav** [comment]
Hello. There were changes made to the back end code as well in superdesk-core repository. I cannot see those changes in this repository. Where can I expect those changes being made. 

Namely there was a semaphore.py in textcheckers/ai and changes in the init.py file as well to be addressed.

https://github.com/canadianpress/superdesk-core/tree/master/superdesk/text_checkers/ai

**Comment by tomaskikutis** [comment]
As I've mentioned in https://github.com/superdesk/superdesk-client-core/pull/4409#issuecomment-1885388635, after I moved front-end code here, 5 more commits were pushed. Those you'll have to move here manually. Most of those commits are one liners so it shouldn't take much effort.

@petrjasek advise how to move back-end files from superdesk-core to this PR.

**Comment by petrjasek** [comment]
I've moved the files here, but couldn't run it locally so not sure it works. and it needs a core change I've made a PR for:
https://github.com/superdesk/superdesk-core/pull/2510
fyi @cpefatimaabdillahi

**Pull request merged**
