### PR TITLE
Add destinations CV [SDCP-251]

### PR DESCRIPTION
**Pull request by karelpetrak**

### CODE REVIEW

**Comment by petrjasek** [comment]
I would rather store psc_code as qcode, no need for another field there:
```ts
{"qcode": "AHN01", "name": "Alaska...", ...}
```
also not sure what destination_type is?

**Comment by karelpetrak** [comment]
> I would rather store psc_code as qcode, no need for another field there:
The problem is that it doesn't seem to be unique :( E.g. "onlin" is there twice (id 116 and 127).

**Comment by petrjasek** [comment]
isn't it just french label?

**Comment by karelpetrak** [comment]
It could be but there other "twins" that have a different pscCodes like  The Associated Press / L'Associated Press
and others which have the same pscCode but different name which do not seem to be language versions (CDNPR = MarketWired and also Globenewswire-CDNPR)

**Comment by karelpetrak** [comment]
It may be intentional or just an error but I found 3 pairs with the same pscCode

**Pull request merged**
