### PR TITLE
FIX: Translated AP items can not be published [SDCP-571]

### PR DESCRIPTION
**Pull request by GyanP**

### CODE REVIEW

**Comment by petrjasek** [comment]
what was the issue actually? how is it fixed? and is there always a tz?

**Comment by petrjasek** [comment]
what I see in logs which seems related is related to location:
https://sentry.sourcefabric.org/share/issue/08f5806c07a146b98af97ae1e4c11593/

**Comment by GyanP** [comment]
> what I see in logs which seems related is related to location:
> https://sentry.sourcefabric.org/share/issue/08f5806c07a146b98af97ae1e4c11593/
> and that's related to place Ottawa

No, it is was another issue. some validation error on publish  like this` dateline: {located: {continent_code: "unknown field", feature_class: "unknown field", name: "unknown field",…}}` that's why it is not allowing the AP item to publish.

**Comment by petrjasek** [comment]
I see, can you also address that keyerror?

**Comment by GyanP** [comment]
In schema of 

> I see, can you also address that keyerror?

Okay, I will address this one also but I think that AP items do not have a location and the location contains the latitude and longnitude so without location, we are unable to translate placeline. however, while handling the **keyerror** we can add a message something like **" Location is required for placeline to be translated"** or something?

**Comment by petrjasek** [comment]
if it's not translated due to missing metadata it's ok imo

**Comment by GyanP** [comment]
okay then should I handle key errors with the message, I specified in the above comment or not?

**Comment by petrjasek** [comment]
I'm not sure, is it possible to translate the article & display the message at the same time?

**Comment by GyanP** [comment]
> I'm not sure, is it possible to translate the article & display the message at the same time?

No, imo it is not possible, we can check it in the logs file only.

**Comment by petrjasek** [comment]
so lets just handle that case in a way that it won't translate it

**Comment by GyanP** [comment]
> so let's just handle that case in a way that it won't translate it

we already handled it here https://github.com/superdesk/superdesk-cp/blob/develop/server/cp/macros/update_translation_metadata_macro.py#L91. do we need to handle that **key error** with a specific message?

**Comment by petrjasek** [comment]
I see, should be good then

**Review by petrjasek — APPROVED** [review]

**Comment by GyanP** [comment]
> so lets just handle that case in a way that it won't translate it

we already handled it here https://github.com/superdesk/superdesk-cp/blob/develop/server/cp/macros/update_translation_metadata_macro.py#L91.

**Pull request merged**
